

/*

LISTA 04 - FÁCIL! EXCETO OS HARDS (29 E 30)

OS EXERCICIOS ABAIXO SÃO PARA TREINAR E MAIS DIFICEIS QUE A LISTA 04. SE ESTIVEREM MUITO DIFICEIS, FAÇAM TODA LISTA 04.

1. FAÇA UM PROGRAMA QUE DADO 10 VALORES DIGITADOS PELO USUARIO, INDIQUE QUAL O MENOR VALOR.

2. FAÇA UM PROGRAMA QUE LEIA 10 NUMEROS INTEIROS E INDIQUE QUANTOS SAO PARES E QUANTOS SAO IMPARES

3. FAÇA UM PROGRAMA QUE MOSTRE TODOS OS DIVISORES DE UM NUMERO

4. FAÇA UM PROGRAMA QUE INDIQUE SE UM NUMERO É PRIMO.

5. FAÇA UM PROGRAMA QUE DADO 5 VALORES, INDIQUE SE ELES FORMAM UMA SEQUENCIA. CONSIDERAREMOS SEQUENCIA QUANDO A DIFERENÇA ENTRE O VALOR E O PROXIMO SE MANTEM. (PA)

6. FAÇA UM PROGRAMA QUE MOSTRE OS 15 PRIMEIROS TERMOS DA SEQUENCIA DE FIBONACCI
    1 1 2 3 5 8 13 21 ...



*/

