/*

FACA UM PROGRAMA EM JAVA QUE, UTILIZANDO LAÇOS DE REPETIÇÃO, CALCULE O VALOR TOTAL DO LANCHE DA FAMÍLIA
PODENDO

- ADICIONAR LANCHE, COM ADICIONAIS
- ADICIONAR BEBIDA

É O CARRINHO / RESTAURANTE DO IFOOD

CRIEM UM MINI CARDAPIO, COM PELO MENOS 3 ITENS, 3 ADICIONAIS, E 3 BEBIDAS.
CADA ITEM, TEM NOME E PREÇO, NO FINAL 
QUERO VER UM "EXTRATO" DO PEDIDO + PREÇO TOTAL DO PEDIDO
*/